### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by liyongjie1002** [obfuscator-llvm/obfuscator#101]
How can I use it, code can be confused only choose obfuscator compiler?

**Comment by sazizbekyants** [comment]
and one more question how can I see the result of obfuscation process ?

**Comment by Naville** [comment]
Yep.
also @sazizbekyants  you can disassemble the binary or tell clang to output obfuscated IR
Example:
``THE/CLANG/YOU/BUILT -WHATEVERFLAGS -S -emit-llvm /PATH/TO/CODE.cpp``,  then something like ``CODE.ll`` is available in current folder. Just open it up in a text editor and see : )

**Comment by sazizbekyants** [comment]
@Naville thanks for replay , but what about if I us it in xcode i.e I mean Integration into Xcode ? where I can see obfuscation result ?


Thank You

**Comment by Naville** [comment]
@sazizbekyants Unfortunately in that case there is not much you could do without modifications to O-LLVM to my best knowledge.
