### ISSUE TITLE
what is the difference between clang from android-NDK and obfuscator??

### ISSUE THREAD

**Issue by harlanc** [obfuscator-llvm/obfuscator#105]
as the title described.

**Comment by harlanc** [comment]
seems that the clang from obfuscator cannot support .altmacro now.
https://reviews.llvm.org/D32523

**Comment by Naville** [comment]
you can just port the passes to clang from svn

**Comment by Naville** [comment]
the core is in lib/Transforms/Obfuscation
Also see  lib/Transforms/Obfuscation/IPO/PassManagerBuilder.cpp if you are still lost feel free to send me a email at admin@mayuyu.io

**Comment by Naville** [comment]
do note, that LLVM's policy did mention that major releases break APIs, so it's probably best for you to fetch both clang and llvm from svn before porting

**Comment by harlanc** [comment]
thx,I just add the commits from clang ,rebuild and the problem is fixed.
