### ISSUE TITLE
No changes happen when using obfuscator???

### ISSUE THREAD

**Issue by harlanc** [obfuscator-llvm/obfuscator#107]
The platform:
Darwin x86_64

The source codes:
`#include <stdlib.h>`
`int main(int argc, char** argv) {`
  `int a = atoi(argv[1]);`
`  if(a == 0)`
  `  return 1;`
 ` else`
   ` return 10;`
 ` return 0;`
`}`
build with the following command:
`./clang  llvm.c -o llvm`

then open llvm with ida64,the IDA view-A:
![2018-01-06 6 06 43](https://user-images.githubusercontent.com/10411078/34638719-99b1fb8e-f30c-11e7-89ab-4886974ca0ec.png)

and the Pseudocode-A
![2018-01-06 6 07 04](https://user-images.githubusercontent.com/10411078/34638720-9a2ff228-f30c-11e7-99f1-b9b77b876a73.png)

add the obfuscator parameters:
`./clang  llvm.c -o llvmobfu -mllvm -fla -mllvm -split -mllvm -split_num=10`

**Comment by harlanc** [comment]
sorry,change happens.

**Comment by ibrahimsadek** [comment]
> sorry,change happens.

Hi, did you remember how you see the change ? I am running the same example. However, I cannot see any change when I open the c script. should I add some more commands ?

**Comment by weirenren** [comment]
@harlanc Hi，咨询一下：用的是破解版的IDA 么，还是 付费版的 IDA Pro? 我用的试用版 Free 版本没有看到 这个可视化逻辑图啊
