### ISSUE TITLE
clang: clang: errorerror: : unsupported option '--noexecstack'unsupported option '--noexecstack'

### ISSUE THREAD

**Issue by harlanc** [obfuscator-llvm/obfuscator#109]
When I use the ollvm clang to compile ,I got the following error:

clang: clang: errorerror: : unsupported option '--noexecstack'unsupported option '--noexecstack'

But when I use the NDK r14b clang,it it successful.

**Comment by Naville** [comment]
You need to port OLLVM to newer toolchains.

**Comment by harlanc** [comment]
thanks. I copy the generated ollvm build folder to my own toolchain folder manually.then the error appears.

The right steps should be to copy the folder to NDK toolchain folder and use make-standalone-toolchain.sh tool to generate the toolchain automatically.
