### ISSUE TITLE
doesn't work for IOS app written in objective c

### ISSUE THREAD

**Issue by Karen0103** [obfuscator-llvm/obfuscator#110]
app build succeed but no obfuscation shown in binaries.

**Comment by Karen0103** [comment]
obfuscation flag  -mllvm -bcf   has been added to Obfuscator Custom Flags  OTHER_CPLUSPLUSFLAGS but no change happens.

Someone knows why?
Thank you!

**Comment by xwren362922604** [comment]
add to Other C Flags

**Comment by exorxw** [comment]
add to `Other C Flags`

**Comment by Karen0103** [comment]
When add flag to **Other C Flags** , compile fail and error is as following:
![screen shot 2018-02-03 at 2 56 42 pm](https://user-images.githubusercontent.com/16543224/35770907-7a9bd4f8-08f2-11e8-903a-66006c39c9a6.png)

**Comment by Karen0103** [comment]
![screen shot 2018-02-03 at 3 27 00 pm](https://user-images.githubusercontent.com/16543224/35771215-c6c21046-08f6-11e8-888a-beb946936437.png)

**Comment by exorxw** [comment]
emmm, maybe you can try this repo:[https://github.com/Qrilee/llvm-obfuscator](https://github.com/Qrilee/llvm-obfuscator)
it based on llvm 5.0 release with ollvm and Armariris

**Comment by Naville** [comment]
You are still using the default toolchain, judging by the screenshot.
Try switch to OLLVM first

**Comment by Karen0103** [comment]
It still does not work and got the same compile error.  When no flag added, the compile succeed.

**Comment by Karen0103** [comment]
That's weird.  I've already changed the toolchain in the build setting.
![screen shot 2018-02-06 at 1 02 08 pm](https://user-images.githubusercontent.com/16543224/35875729-2ebdb756-0b3e-11e8-8d41-9b13dc0b5cdc.png)

**Comment by Karen0103** [comment]
Thank you guys.  I've changed the toolchain to OLLVM, it still not work. Then, I try override CC to point to the OLLVM clang path by manually add it in User-Define Setting. Finally, it works!

Anyway, thank you so much!
