### ISSUE TITLE
How to obfuscate the source code? (with multiple headers)

### ISSUE THREAD

**Issue by onatkeser** [obfuscator-llvm/obfuscator#173]
I'd like to obfuscate my C++ source codes with multiple header files but I could not figure out how to do it?

**Comment by onatkeser** [comment]
In other words, as we can do it here: https://picheta.me/obfuscator (+with multiple headers) in an offline environment.

**Comment by cryptopathe** [comment]
Hey! O-LLVM is not a source code obfuscator, it can only produce obfuscated IR or executables.
