### ISSUE TITLE
string encryption error!

### ISSUE THREAD

**Issue by yfw123** [obfuscator-llvm/obfuscator#21]
I compiled file information:
Source Files:
#include 
int main()
{
printf("hello llvm\n");
return 1;

}

Application.mk:
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
APP_ABI := armeabi
NDK_TOOLCHAIN_VERSION := clang3.5
include $(BUILD_EXECUTABLE)

Android.mk:
LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE := test
LOCAL_SRC_FILES := test.c
LOCAL_CFLAGS := -mllvm -xse

Error Messages:
clang: /LLVM/obfuscator/lib/IR/Value.cpp:352: void llvm::Value::replaceAllUsesWith(llvm::Value*): Assertion `New->getType() == getType() && "replaceAllUses of value with new value of different type!"' failed.

Why does this error Tips?
Thank you!

**Comment by yag00** [comment]
Hi.

This pass has never been tested with llvm 3.5 try 3.4!

Regards

**Comment by yfw123** [comment]
3.4 success! Thank you!

**Comment by wustwg** [comment]
why my 3.4 doesn't work?Console shows "Did you mean '-fla'"
