### ISSUE TITLE
Cannot build on Big endian platform

### ISSUE THREAD

**Issue by tranhuanltv** [obfuscator-llvm/obfuscator#24]
When I build on PowerPC 64 this error happen
[ 23%] Building CXX object lib/Transforms/Obfuscation/CMakeFiles/LLVMObfuscation.dir/BogusControlFlow.cpp.o
In file included from /home/llvm-obfuscator/obfuscator/include/llvm/Transforms/Obfuscation/Substitution.h:26:0,
                 from /home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/Substitution.cpp:15:
/home/u0015999/llvm-obfuscator/obfuscator/include/llvm/CryptoUtils.h:80:2: error: #error "Unknown endianness of the compilation platform, check this header aes_encrypt.h"
 #error                                                                         \
  ^
In file included from /home/llvm-obfuscator/obfuscator/include/llvm/Transforms/Obfuscation/BogusControlFlow.h:37:0,
                 from /home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/BogusControlFlow.cpp:93:
/home/llvm-obfuscator/obfuscator/include/llvm/CryptoUtils.h:80:2: error: #error "Unknown endianness of the compilation platform, check this header aes_encrypt.h"
 #error                                                                         \
  ^
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp: In member function ‘unsigned int llvm::CryptoUtils::scramble32(unsigned int, const char*)’:
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp:545:20: error: ‘LOAD32H’ was not declared in this scope
   LOAD32H(tmpA, key);
                    ^
/home//llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp: In member function ‘void llvm::CryptoUtils::inc_ctr()’:
/home/u0015999/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp:658:25: error: ‘LOAD64H’ was not declared in this scope
   LOAD64H(iseed, ctr + 8);
                         ^
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp:660:26: error: ‘STORE64H’ was not declared in this scope
   STORE64H(ctr + 8, iseed);
                          ^
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp: In member function ‘uint32_t llvm::CryptoUtils::get_uint32_t()’:
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp:735:19: error: ‘LOAD32H’ was not declared in this scope
   LOAD32H(ret, tmp);
                   ^
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp: In member function ‘uint64_t llvm::CryptoUtils::get_uint64_t()’:
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp:748:19: error: ‘LOAD64H’ was not declared in this scope
   LOAD64H(ret, tmp);
                   ^
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp: In member function ‘void llvm::CryptoUtils::aes_compute_ks(uint32_t*, const char*)’:
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp:787:19: error: ‘LOAD32H’ was not declared in this scope
   LOAD32H(ks[0], k);
                   ^
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp: In member function ‘void llvm::CryptoUtils::aes_encrypt(char*, const char*, const uint32_t*)’:
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp:819:25: error: ‘LOAD32H’ was not declared in this scope
   LOAD32H(state0, in + 0);
                         ^
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp:868:27: error: ‘STORE32H’ was not declared in this scope
   STORE32H(out + 0, state0);
                           ^
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp: In static member function ‘static int llvm::CryptoUtils::sha256_compress(llvm::CryptoUtils::sha256_state*, unsigned char*)’:
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp:921:32: error: ‘LOAD32H’ was not declared in this scope
     LOAD32H(W[i], buf + (4 * i));
                                ^
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp: In member function ‘int llvm::CryptoUtils::sha256_done(llvm::CryptoUtils::sha256_state*, unsigned char*)’:
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp:1064:36: error: ‘STORE64H’ was not declared in this scope
   STORE64H(md->buf + 56, md->length);
                                    ^
/home/llvm-obfuscator/obfuscator/lib/Transforms/Obfuscation/CryptoUtils.cpp:1069:41: error: ‘STORE32H’ was not declared in this scope
     STORE32H(out + (4 * i), md->state[i]);

**Comment by pyknite** [comment]
There is a bug in the endings detection... We are working on it

**Comment by tranhuanltv** [comment]
I have pull request for this already. you may review and consider for merge it

**Comment by cryptopathe** [comment]
Pull request merged.

**Comment by XiaoR** [comment]
When I build on ARM 64 this error happen， I'm on the llvm-4.0 branch

In file included from /home/ubuntu/obfuscator/include/llvm/Transforms/Obfuscation/BogusControlFlow.h:37:0,
                 from /home/ubuntu/obfuscator/lib/Transforms/IPO/PassManagerBuilder.cpp:42:
/home/ubuntu/obfuscator/include/llvm/CryptoUtils.h:84:2: error: #error "Unknown endianness of the compilation platform, check this header aes_encrypt.h"

**Comment by LostBenjamin** [comment]
Errors also occur when I built on ARM 32 with llvm-3.4 branch:

In file included from /root/obfuscator/include/llvm/Transforms/Obfuscation/Flattening.h:27:0,
                 from /root/obfuscator/lib/Transforms/Obfuscation/CgfFunction.cpp:1:
/root/obfuscator/include/llvm/PrngAESCtr.h:80:2: error: #error "Unknown endianness of the compilation platform, check this header aes_encrypt.h"
 #error "Unknown endianness of the compilation platform, check this header aes_encrypt.h"
