### ISSUE TITLE
How to use o-llvm with xcodeBuild or xctool

### ISSUE THREAD

**Issue by AHappyFish** [obfuscator-llvm/obfuscator#27]
I want to use the command line tool  build my project ,like that:
`xctool -project test.xcodeproj -scheme test -toolchain obfuscator3.4` or
`xctool -project test.xcodeproj -scheme test -toolchain obfuscator3.4`
it dosen't work

**Comment by pyknite** [comment]
Did you create the plugin (https://github.com/obfuscator-llvm/obfuscator/wiki/Installation#integration-into-xcode)? It should works this way.

The tutoriel is not up to date since the last update of Xcode, but it's basically the same process. I'm going to refresh it later.

**Comment by AHappyFish** [comment]
Yes,I have created the plugin,but just when I open the xcode and changed xcode-buildsettings ,the command line works,   especially， is there anyway can use o-llvm with a xcode-project without create a plugin

**Comment by pyknite** [comment]
No, you can't use obfuscation without the plugin.
I'll check for xctool if it's possible to indicate the compiler to use.
