### ISSUE TITLE
unknown dummy loop in compiled files

### ISSUE THREAD

**Issue by dmtch** [obfuscator-llvm/obfuscator#29]
Please look at this malware sample (i.g. function on VA 0x401000): http://rghost.net/private/7tx8KzHd4/2929b91a7f699d048f48514713b31df4
It looks like compiled on ollvm, right? Here is very similar pattern of control flow flattening technique and instructions substitutions. But in addition we can see these code snippets (blue blocks on this pic):
![untitled](https://cloud.githubusercontent.com/assets/13199836/8522122/e417e6c8-23b8-11e5-8259-0702fad5fdd4.png) 
Does ollvm such constants initializations?

**Comment by pyknite** [comment]
Looks weird, but I never saw that in a binary file compiled with o-lllvm. And we don't do this kind of initialisations.

Maybe some optimizations have a weird behaviour with the flattening, but I don't think so.
