### ISSUE TITLE
iOS: Obfuscator clang does not respect -isysroot and/or has incorrect assumptions about the platform it is building for

### ISSUE THREAD

**Issue by H2CO3** [obfuscator-llvm/obfuscator#32]
I am trying to compile an iOS Xcode project which contains C++ code using Obfuscator-LLVM. I have version 3.6 of the tool. I have followed the tutorial on the wiki and have successfully installed Obfuscator-LLVM. I have changed the compiler in my Xcode project from Apple LLVM 6.0 to Obfuscator-LLVM 3.6. When I am building the project, however, I get an error relating to an allegedly non-existent header file. Here's the compiler invocation from Xcode (I am using Xcode 6.4 on Yosemite):

    /Users/H2CO3/Projects/obfuscator/build/bin/clang -x c++ -arch armv7 -fmessage-length=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -std=c++11 -stdlib=libc++ -Wno-trigraphs -fpascal-strings -O0 -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-non-virtual-dtor -Wno-overloaded-virtual -Wno-exit-time-destructors -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wno-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wno-shorten-64-to-32 -Wno-newline-eof -Wno-c++11-extensions -DDEBUG -D__APPLE__ -DCPU_RISC -DHAVE_STDLIB_H -DFIXED_POINT -DNODLL -DCOCOA -DIOS=1 -DUSE_ARES -DUSE_OPENSSL -DUSE_SSL -DTARGET_OS_IPHONE -DWEBRTC_POSIX -DPUBLISH_BY_REGISTRATION -DENFORCE_CTRMODE -DUSE_NATIVE_IOS_TRANSPORT -DHAVE_PTHREAD -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.4.sdk -fexceptions -fstrict-aliasing -Wdeprecated-declarations -Winvalid-offsetof -g -Wno-sign-conversion -iquote /Users/H2CO3/Library/Developer/Xcode/DerivedData/<REDACTED>-asuhqbittuwyjediewslofuppzrs/Build/Intermediates/<REDACTED>.build/Debug-iphoneos/<REDACTED>.build/<REDACTED>-generated-files.hmap -I/Users/H2CO3/Library/Developer/Xcode/DerivedData/<REDACTED>-asuhqbittuwyjediewslofuppzrs/Build/Intermediates/<REDACTED>.build/Debug-iphoneos/<REDACTED>.build/<REDACTED>-own-target-headers.hmap -I/Users/H2CO3/Library/Developer/Xcode/DerivedData/<REDACTED>-asuhqbittuwyjediewslofuppzrs/Build/Intermediates/<REDACTED>.build/Debug-iphoneos/<REDACTED>.build/<REDACTED>-all-target-headers.hmap -iquote /Users/H2CO3/Library/Developer/Xcode/DerivedData/<REDACTED>-asuhqbittuwyjediewslofuppzrs/Build/Intermediates/<REDACTED>.build/Debug-iphoneos/<REDACTED>.build/<REDACTED>-project-headers.hmap -iquote../../Components/jrtplib/src -iquote../../Components -iquote../../Components/Util -iquote../../Components/resip -iquote../../../lib/openssl/include -iquote../../../lib/srtp/include -I/Users/H2CO3/Library/Developer/Xcode/DerivedData/<REDACTED>-asuhqbittuwyjediewslofuppzrs/Build/Products/include -I../../Components/webrtc/signal_processing_library -I../../Components/jrtplib/src -I../../Components -I../../Components/Util -I../../Components/resip -I../../../lib/openssl/include -I../../Components/webrtc -IHeaders -I../../../lib/srtp/ios/include -I../../../lib -I../../../../<REDACTED>/Pods/BuildHeaders/SQLCipher -I/Users/H2CO3/Library/Developer/Xcode/DerivedData/<REDACTED>-asuhqbittuwyjediewslofuppzrs/Build/Intermediates/<REDACTED>.build/Debug-iphoneos/<REDACTED>.build/DerivedSources/armv7 -I/Users/H2CO3/Library/Developer/Xcode/DerivedData/<REDACTED>-asuhqbittuwyjediewslofuppzrs/Build/Intermediates/<REDACTED>.build/Debug-iphoneos/<REDACTED>.build/DerivedSources -F/Users/H2CO3/Library/Developer/Xcode/DerivedData/<REDACTED>-asuhqbittuwyjediewslofuppzrs/Build/Products -DSQLITE_HAS_CODEC -include /Users/H2CO3/Library/Developer/Xcode/DerivedData/<REDACTED>-asuhqbittuwyjediewslofuppzrs/Build/Intermediates/PrecompiledHeaders/<REDACTED>_Prefix-gsbkjbroiirpaiguuicwnmndlpry/<REDACTED>_Prefix.pch -c /Users/H2CO3/Projects/<REDACTED>-iOS/<REDACTED>/src/Components/ICE/ICEAddress.cpp -o /Users/H2CO3/Library/Developer/Xcode/DerivedData/<REDACTED>-asuhqbittuwyjediewslofuppzrs/Build/Intermediates/<REDACTED>.build/Debug-iphoneos/<REDACTED>.build/Objects-normal/armv7/ICEAddress.o

The error is that the `<algorithm>` header file cannot be found. I checked using `find`, however, that the header file in question exists in the iOS SDK directory hierarchy. When I have added the immediate directory which contains the header file (using the `-I` compiler flag), it has found the header, although it then complained about other headers in other directories. When I added those as well, the compiler was now emitting syntax errors found in system headers. That is obviously nonsense, because I have compiled the project successfully using the stock `clang` that comes with Xcode. So I think the `clang` that comes with Obfuscator-LLVM doesn't respect the `-isysroot` flag or it has some misconceptions about which platform it is compiling for (or both).

**Comment by H2CO3** [comment]
Hi! Is there any progress on this? Thanks!

**Comment by cryptopathe** [comment]
The actual version of ollvm (3.6.1) is not based on Apple's one, but on the initial LLVM source tree, which explains why it is not 100% user-friendly to build iOS apps. As we are very busy with our company (cf. https://strong.codes), we don't plan to port ollvm on Apple's version for the moment.
