### ISSUE TITLE
nullable from sdk9.1 ios unknown from obfusctor

### ISSUE THREAD

**Issue by emarce** [obfuscator-llvm/obfuscator#36]
I have a projet buit on iphone using sdk 8.1 and obfuscator (clang) as compiler : ok, it is working fine
Recently I moved my project to use it with ios SDK9.1 => nullable (introduced by apple with ios 9.1) is unknown by the compiler

**Comment by pyknite** [comment]
Hi,

LLVM 3.6.1 does not support the most recent SDK from Apple.
We do not plan to port our open-source obfuscator for the moment to the last LLVM version.
If you are interested, we have an updated commercial version available at https://strong.codes.
