### ISSUE TITLE
max_align_t typedef different between obfusctor and sdk9.1 from ios

### ISSUE THREAD

**Issue by emarce** [obfuscator-llvm/obfuscator#37]
I have a projet buit on iphone using sdk 8.1 and obfuscator (clang) as compiler : ok, it is working fine
Recently I moved my project to use it with ios SDK9.1 => compilation error due to the following typedef max_align_t
We can find this typedef in stddef.h of the obfusctor and the one from de sdk9.1, but it has 2 different size : long double vs double
This typedef was not defined with ios sdk8

**Comment by pyknite** [comment]
See #36
