### ISSUE TITLE
Error: Build Firefox with obfuscator-llvm 

### ISSUE THREAD

**Issue by pfsun** [obfuscator-llvm/obfuscator#42]
I try to build firefox with obfuscator-llvm (-mllvm -bcf). Now, I always meet one error. Could you give me some suggestions how to solve this error? 
Thank you very much!

c -fdiagnostics-show-option -mllvm -bcf -o AsmJSCache.o -x c++ /home/sun/mozilla-central/dom/asmjscache/AsmJSCache.cpp
 1:38.58 1.	<eof> parser at end of file
 1:38.58 2.	Code generation
 1:38.58 3.	Running pass 'Function Pass Manager' on module '/home/sun/mozilla-central/dom/asmjscache/AsmJSCache.cpp'.
 1:38.58 4.	Running pass 'X86 Assembly / Object Emitter' on function '@_ZThn64_N7mozilla3dom10asmjscache12_GLOBAL__N_114ParentRunnable19DirectoryLockFailedEv'
 1:39.99 clang-3.6: error: unable to execute command: Aborted (core dumped)
 1:39.99 clang-3.6: error: clang frontend command failed due to signal (use -v to see invocation)
 1:39.99 Obfuscator-LLVM clang version 3.6.1 (tags/RELEASE_361/final) (based on Obfuscator-LLVM 3.6.1)
 1:39.99 Target: x86_64-unknown-linux-gnu
 1:39.99 Thread model: posix
 1:39.99 clang-3.6: note: diagnostic msg: PLEASE submit a bug report to http://o-llvm.org and include the crash backtrace, preprocessed source, and associated run script.
 1:40.90 clang-3.6: note: diagnostic msg:
 1:40.90 ********************
 1:40.90 
 1:40.90 PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
 1:40.90 Preprocessed source(s) and associated run script(s) are located at:
 1:40.90 clang-3.6: note: diagnostic msg: /tmp/AsmJSCache-87d5d1.cpp
 1:40.90 clang-3.6: note: diagnostic msg: /tmp/AsmJSCache-87d5d1.sh
 1:40.90 clang-3.6: note: diagnostic msg:
 1:40.90 
 1:40.90 ********************
 1:40.90 
 1:40.90 In the directory  /home/sun/mozilla-central/obj-x86_64-unknown-linux-gnu/dom/asmjscache
 1:40.90 The following command failed to execute properly:
 1:40.90 /home/sun/project/obfuscator/build/bin/clang++ -o AsmJSCache.o -c -I/home/sun/mozilla-central/obj-x86_64-unknown-linux-gnu/dist/stl_wrappers -I/home/sun/mozilla-central/obj-x86_64-unknown-linux-gnu/dist/system_wrappers -include /home/sun/mozilla-central/config/gcc_hidden.h -DDEBUG=1 -DTRACING=1 -DOS_POSIX=1 -DOS_LINUX=1 -DSTATIC_EXPORTABLE_JS_API -DMOZILLA_INTERNAL_API -DIMPL_LIBXUL -I/home/sun/mozilla-central/dom/asmjscache -I/home/sun/mozilla-central/obj-x86_64-unknown-linux-gnu/dom/asmjscache -I/home/sun/mozilla-central/obj-x86_64-unknown-linux-gnu/ipc/ipdl/_ipdlheaders -I/home/sun/mozilla-central/ipc/chromium/src -I/home/sun/mozilla-central/ipc/glue -I/home/sun/mozilla-central/obj-x86_64-unknown-linux-gnu/dist/include -I/home/sun/mozilla-central/obj-x86_64-unknown-linux-gnu/dist/include/nspr -I/home/sun/mozilla-central/obj-x86_64-unknown-linux-gnu/dist/include/nss -fPIC -DMOZILLA_CLIENT -include /home/sun/mozilla-central/obj-x86_64-unknown-linux-gnu/mozilla-config.h -MD -MP -MF .deps/AsmJSCache.o.pp -Qunused-arguments -Qunused-arguments -Wall -Wempty-body -Wignored-qualifiers -Woverloaded-virtual -Wpointer-arith -Wtype-limits -Wclass-varargs -Wsometimes-uninitialized -Wunreachable-code -Wno-invalid-offsetof -Wno-inline-new-delete -Wno-unused-local-typedef -Wno-c++0x-extensions -Wno-extended-offsetof -Wno-unknown-warning-option -Wno-return-type-c-linkage -mllvm -bcf -fno-exceptions -fno-strict-aliasing -fno-rtti -fno-exceptions -fno-math-errno -std=gnu++0x -pthread -pipe -g -fno-omit-frame-pointer /home/sun/mozilla-central/dom/asmjscache/AsmJSCache.cpp
 1:40.90 make[5]: *** [AsmJSCache.o] Error 1
 1:40.90 make[4]: *** [dom/asmjscache/target] Error 2
 1:40.90 make[4]: *** Waiting for unfinished jobs....
 1:50.71 libdom_datastore.a.desc
 1:59.19 librdf_base.a.desc
 2:06.87 libview.a.desc
 2:06.89 make[3]: *** [compile] Error 2
 2:06.89 make[2]: *** [default] Error 2
 2:06.89 make[1]: *** [realbuild] Error 2
 2:06.89 make: *** [build] Error 2

**Comment by cryptopathe** [comment]
To better understand what happened, could you please attach the temporary files (the name will vary for a new compilation) to the issue? Thanks !
 
1:40.90 clang-3.6: note: diagnostic msg: /tmp/AsmJSCache-87d5d1.cpp
1:40.90 clang-3.6: note: diagnostic msg: /tmp/AsmJSCache-87d5d1.sh

**Comment by cryptopathe** [comment]
It looks safe to close this one.
