### ISSUE TITLE
Does it support Xcode 7 ?

### ISSUE THREAD

**Issue by lin493369** [obfuscator-llvm/obfuscator#43]
Does it support Xcode 7 ?
Can anyone clearly tell me whether obfuscator-llvm  support Xcode 7？

**Comment by jowehrli** [comment]
Hi,

The obfuscator-llvm is not currently actively developed.

We are, for the moment, focusing on our commercial version, which is
available at https://strong.codes/.

Our commercial product works with the latest version of Xcode.

Greetings,

Wehrli Johan

2016-03-22 10:35 GMT+01:00 小袋子 <notifications@github.com>:

**Comment by lin493369** [comment]
Does it mean that  obfuscator-llvm don't support the Xcode 7?But your commercial product is support?

**Comment by jowehrli** [comment]
Yes our commercial product support Xcode 7.

Meilleures salutations,

Wehrli Johan

2016-03-22 11:01 GMT+01:00 小袋子 <notifications@github.com>:

**Comment by lin493369** [comment]
OK
 Thanks a lot!
