### ISSUE TITLE
About the clang path

### ISSUE THREAD

**Issue by springlo** [obfuscator-llvm/obfuscator#44]
in Obfuscator.xcspec:

ExecPath = “/Users/lc/Desktop/Obfuscator/build/bin/clang-3.6”

when I build that get a error:

`clang-3.6: error: unknown argument: '-gmodules'
clang-3.6: error: unknown argument: '-fembed-bitcode-marker'
Command /Users/lc/Desktop/Obfuscator/build/bin/clang-3.6 failed with exit code 1`

**Comment by springlo** [comment]
Will it be the wrong path?

**Comment by springlo** [comment]
Who can help me?  thanks

**Comment by pyknite** [comment]
Hi,

In your Xcode settings you have to set "Enable Bitcode" NO.

Cheers,
Julien

**Comment by springlo** [comment]
Hi, I try it , and now get the error
 `clang-3.6: error: unknown argument: '-gmodules'`

**Comment by pyknite** [comment]
Hi,

That is because obfuscator-llvm does not support recent version of Xcode.
You should try to disable this flag within Xcode (I don't know which option enable/disable it).

Cheers,
Julien

**Comment by springlo** [comment]
the version of my Xcode is 7.3 ,
I think that you said is `Enable Clang Module Debugging`  change to NO.
and get error:
`In file included from /Users/lc/Desktop/httpsDemo/httpsDemo/AppDelegate.m:9:
/Users/lc/Desktop/httpsDemo/httpsDemo/AppDelegate.h:9:9: fatal error: could not build module 'UIKit'
#import <UIKit/UIKit.h>
 ~~~~~~~^
7 errors generated.`

**Comment by pyknite** [comment]
HI,

As I said, this clang version does not support recent version of Xcode.

If you are interested in a more recent version, with more obfuscation available, you can check our website: https://strong.codes
