### ISSUE TITLE
No target specified and no makefile found

### ISSUE THREAD

**Issue by PReeeT** [obfuscator-llvm/obfuscator#45]
On executing make -j5. I end up with this error. 
I also tried running this command outside the build folder but still the same issue. 
Can anyone help me understand how can I correct this.

**Comment by cryptopathe** [comment]
On which platform/OS are you trying to build OLLVM? Do you have properly generated the build folder with cmake?

**Comment by PReeeT** [comment]
I am installing OLLVM in ubuntu 14.04 (VM). Yes, I could generate the build folder with cmake. After executing cmake I see 1 file named llvm-lit in build/bin/. And when I run make command I end up with the mentioned error.

**Comment by PReeeT** [comment]
Apparently cmake execution is not successful. I got following errors. 
```
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: Internal CMake error, TryCompile configure of CMake failed
CMake Error at projects/complier-rt/CMakeLists.txt.215 (message):
```
