### ISSUE TITLE
question about openmp

### ISSUE THREAD

**Issue by snigoal** [obfuscator-llvm/obfuscator#46]
I use o-llvm (llvm 3.6) to compile an static library, got an error about "omp.h" like this:
`fatal error: 'omp.h' file not found`
I try to copy an omp.h into $NDK_PATH/toolchains/llvm-3.6/prebuilt/linux-x86/lib/clang/3.6/include but not solve the problem.
then  I look into llvm and OpenMP official website, what I find is shown bellow:
[for Clang 3.6](http://llvm.org/releases/3.6.0/tools/clang/docs/ReleaseNotes.html#openmp-language-changes-in-clang)

> Clang 3.6 contains codegen for many individual OpenMP pragmas, but combinations are not completed yet.

[for Clang 3.7](http://llvm.org/releases/3.7.0/tools/clang/docs/ReleaseNotes.html#openmp-support)

> OpenMP 3.1 is fully supported, but disabled by default. To enable it, please use the -fopenmp=libomp command line option.

[for Clang 3.8](http://llvm.org/releases/3.8.0/tools/clang/docs/ReleaseNotes.html#openmp-support-in-clang)

> OpenMP 3.1 is fully supported and is enabled by default with -fopenmp which now uses the Clang OpenMP library instead of the GCC OpenMP library.

so I think Clang3.6 does not support OpenMP directly. Is there anyway Clang3.6 could support OpenMP when using NDK and [o-llvm](https://github.com/obfuscator-llvm/obfuscator) to build android c libraries?

**Comment by snigoal** [comment]
I have solved this problem by copying a omp.h file into jni folder.
so Clang 3.6 should be supportting OpenMP but have not include OpenMP header files originally.

**Comment by pyknite** [comment]
We did not include openmp in obfuscater-llvm, you can find it here (for example for 3.6): http://llvm.org/releases/download.html#3.6.0

Cheers,
