### ISSUE TITLE
LOCAL_CFLAGS on android

### ISSUE THREAD

**Issue by laminsk** [obfuscator-llvm/obfuscator#48]
Thanks for the project, I've just tried using v3.6.1 llvm-obfuscator and clang is compilining LOCAL_CFLAGS :=  -mllvm -sub -mllvm -fla -mllvm -bcf arguments which was previously working fine with v3.5. I'm using this demo example project (https://github.com/Fuzion24/AndroidObfuscation-NDK). Any help will be greatly appreciated. Thanks

**Comment by cryptopathe** [comment]
So, what is the issue?

**Comment by laminsk** [comment]
Thanks for the reply. This is the error I get in Android studio.

 clang (LLVM option parsing): Unknown command line argument '-bcf'.  Try: 'clang (LLVM option parsing) -help'
clang (LLVM option parsing): Did you mean '-help'?

Previously, I passes these arguments and it always works. 

"LOCAL_CFLAGS := -mllvm -xse -mllvm -sub -mllvm -fla -mllvm -bcf"

**Comment by cryptopathe** [comment]
You are very probably pointing Android Studio build system to the wrong clang binary.

**Comment by laminsk** [comment]
Thanks for the reply. May I ask this tutorial is still valid for v3.6.1 http://fuzion24.github.io/android/obfuscation/ndk/llvm/o-llvm/2014/07/27/android-obfuscation-o-llvm-ndk/

**Comment by cryptopathe** [comment]
Probably not. As of today, Android Studio relies on graddle, which is a different build system.

**Comment by Nodial** [comment]
@laminsk I develop my .so library using Android Studio, then I copy the c/cpp files inside a jni folder of the above mentioned tutorial, then I compile the .so library in linux using clang obfuscator, then I replace the obfuscated library inside the apk file and resign it jarsigner

**Comment by laminsk** [comment]
@Nodial  @cryptopathe  Thanks both for the helping hands. I've now managed to get it working in android studio. "LOCAL_CFLAGS := -mllvm -sub  -mllvm -fla -mllvm -bcf"  One quick final question if you don't mind, is there a way to obfuscate the fixed string? For instance,  "const unsigned char *reqname = "fixedstring";" They are still readable at the moment, in the past I use "-mllvm -xse" and it used to obfuscate the string in source file. 

Many Thanks for your help.
