### ISSUE TITLE
o-llvm with Xcode  

### ISSUE THREAD

**Issue by Carlinho89** [obfuscator-llvm/obfuscator#49]
I'm having a real hard time using llvm obfuscator in Xcode.. I don't understand why, after creating the plugin for it and selecting it in my build settings, I can't compile because clang is giving this "unknown arguments" errors. 

`clang-3.4: error: unknown argument: '-gmodules'
clang-3.4: error: unknown argument: '-fbuild-session-file=/Users/user/Library/Developer/Xcode/DerivedData/ModuleCache/Session.modulevalidation'
clang-3.4: error: unknown argument: '-fmodules-validate-once-per-build-session'
Command /Users/user/Thesis/llvm_obfuscator/obfuscator/build/bin/clang failed with exit code 1`

any possible solution?

I'm using Xcode 7.3,
llvm 3.4

I already tried adding `-Qunused-arguments` in CFlags and CPPFlags.

**Comment by pyknite** [comment]
Hi,

obfuscater-Llvm is not currently actively developed.

We are, for the moment, focusing on our commercial version, which is
available at https://strong.codes/.

Our commercial product works with the latest version of Xcode.

Cheers
