### ISSUE TITLE
unrecognized command line option '-mllvm'

### ISSUE THREAD

**Issue by wangzh7678** [obfuscator-llvm/obfuscator#50]
wang@ubuntu:~/Downloads/hello/jni$ ndk-build -B
[armeabi] Compile thumb  : hello <= hello.c
[armeabi] Executable     : hello
[armeabi] Install        : hello => libs/armeabi/hello
[x86] Compile        : hello <= hello.c
[x86] Executable     : hello
[x86] Install        : hello => libs/x86/hello
[arm64-v8a] Compile        : hello <= hello.c
aarch64-linux-android-gcc: error: unrecognized command line option '-mllvm'
aarch64-linux-android-gcc: error: unrecognized command line option '-sub'
aarch64-linux-android-gcc: error: unrecognized command line option '-mllvm'
aarch64-linux-android-gcc: error: unrecognized command line option '-fla'
aarch64-linux-android-gcc: error: unrecognized command line option '-mllvm'
aarch64-linux-android-gcc: error: unrecognized command line option '-bcf'

the android.mk's cotent:

LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)
LOCAL_MODULE    := hello
LOCAL_SRC_FILES := hello.c
LOCAL_CFLAGS := -mllvm -sub -mllvm -fla -mllvm -bcf 
include $(BUILD_EXECUTABLE)

**Comment by jowehrli** [comment]
Hi,

This is because you are not calling o-llvm executable but gcc
(aarch64-linux-android-gcc).

You need to create your own toolchain with the o-llvm clang executable
(generally clang, clang++ and clang3.8).

Greetings,

Wehrli Johan

2016-08-02 11:29 GMT+02:00 wangzh7678 <notifications@github.com>:

**Comment by wangzh7678** [comment]
@jowehrli   thanks!
 I've created a folder named ‘aarch64-linux-android-wangzh’,it contain 'config.mk' and 'setup.mk' .
part of setup.mk‘s content:
LLVM_VERSION := 3.6
LLVM_NAME := wangzh-llvm-$(LLVM_VERSION)
LLVM_TOOLCHAIN_ROOT := $(NDK_ROOT)/toolchains/$(LLVM_NAME)
LLVM_TOOLCHAIN_PREBUILT_ROOT := $(call host-prebuilt-tag,$(LLVM_TOOLCHAIN_ROOT))
LLVM_TOOLCHAIN_PREFIX := $(LLVM_TOOLCHAIN_PREBUILT_ROOT)/bin/

TOOLCHAIN_VERSION := 4.9
TOOLCHAIN_NAME := aarch64-linux-android-$(TOOLCHAIN_VERSION)
TOOLCHAIN_ROOT := $(NDK_ROOT)/toolchains/$(TOOLCHAIN_NAME)
TOOLCHAIN_PREBUILT_ROOT := $(call host-prebuilt-tag,$(TOOLCHAIN_ROOT))
TOOLCHAIN_PREFIX := $(TOOLCHAIN_PREBUILT_ROOT)/bin/aarch64-linux-android-

TARGET_CC := $(LLVM_TOOLCHAIN_PREFIX)clang$(HOST_EXEEXT)
TARGET_CXX := $(LLVM_TOOLCHAIN_PREFIX)clang++$(HOST_EXEEXT)
LLVM_TRIPLE := aarch64-none-linux-android
......

is anything wrong? Thanks a lot!

**Comment by wangzh7678** [comment]
LLVM_VERSION := 3.6
LLVM_NAME := wangzh-llvm-$(LLVM_VERSION)
LLVM_TOOLCHAIN_ROOT := $(NDK_ROOT)/toolchains/$(LLVM_NAME)
LLVM_TOOLCHAIN_PREBUILT_ROOT := $(call host-prebuilt-tag,$(LLVM_TOOLCHAIN_ROOT))
LLVM_TOOLCHAIN_PREFIX := $(LLVM_TOOLCHAIN_PREBUILT_ROOT)/bin/

TOOLCHAIN_VERSION := 4.9
TOOLCHAIN_NAME := aarch64-linux-android-$(TOOLCHAIN_VERSION)
TOOLCHAIN_ROOT := $(NDK_ROOT)/toolchains/$(TOOLCHAIN_NAME)
TOOLCHAIN_PREBUILT_ROOT := $(call host-prebuilt-tag,$(TOOLCHAIN_ROOT))
TOOLCHAIN_PREFIX := $(TOOLCHAIN_PREBUILT_ROOT)/bin/aarch64-linux-android-

TARGET_CC := $(LLVM_TOOLCHAIN_PREFIX)clang$(HOST_EXEEXT)
TARGET_CXX := $(LLVM_TOOLCHAIN_PREFIX)clang++$(HOST_EXEEXT)

LLVM_TRIPLE := aarch64-none-linux-android

TARGET_CFLAGS := \
    -gcc-toolchain $(call host-path,$(TOOLCHAIN_PREBUILT_ROOT)) \
    -target $(LLVM_TRIPLE) \
    -ffunction-sections \
    -funwind-tables \
    -fstack-protector \
    -fpic \
    -Wno-invalid-command-line-argument \
    -Wno-unused-command-line-argument \
    -no-canonical-prefixes

TARGET_C_INCLUDES := \
    $(SYSROOT_INC)/usr/include

TARGET_LDFLAGS += \
    -gcc-toolchain $(call host-path,$(TOOLCHAIN_PREBUILT_ROOT)) \
    -target $(LLVM_TRIPLE) \
    -no-canonical-prefixes

TARGET_arm64_release_CFLAGS :=  -O2 \
                                -g \
                                -DNDEBUG \
                                -fomit-frame-pointer \
                                -fstrict-aliasing

TARGET_arm64_debug_CFLAGS := $(TARGET_arm64_release_CFLAGS) \
                             -O0 \
                             -UNDEBUG \
                             -fno-omit-frame-pointer \
                             -fno-strict-aliasing

# This function will be called to determine the target CFLAGS used to build
# a C or Assembler source file, based on its tags.
#
TARGET-process-src-files-tags = \
$(eval __debug_sources := $(call get-src-files-with-tag,debug)) \
$(eval __release_sources := $(call get-src-files-without-tag,debug)) \
$(call set-src-files-target-cflags, $(__debug_sources), $(TARGET_arm64_debug_CFLAGS)) \
$(call set-src-files-target-cflags, $(__release_sources),$(TARGET_arm64_release_CFLAGS)) \

**Comment by jowehrli** [comment]
In my case, I needed the LLVM_TOOLCHAIN_PATH option.

LLVM_TOOLCHAIN_PATH := /Path/to/clang/bin/

Meilleures salutations,

Wehrli Johan

2016-08-02 13:25 GMT+02:00 wangzh7678 <notifications@github.com>:

**Comment by wangzh7678** [comment]
it doesn't work!!  I'm crazy!

**Comment by wangzh7678** [comment]
@jowehrli can you post your setup.mk's content?thanks!

**Comment by jowehrli** [comment]
I can send you this .mk file, this is the only one I had on my machine (I
do not develop anything in Android right now).

This is the application.mk from Signal (
https://github.com/WhisperSystems/Signal-Android).

The only thing that I needed to change in the ndk was to create some
wrapper in order to call my clang (just create an sh file that do a
redirection).

Greetings,

Wehrli Johan

2016-08-19 4:42 GMT+02:00 wangzh7678 <notifications@github.com>:

**Comment by wangzh7678** [comment]
@jowehrli thanks！
