### ISSUE TITLE
how to apply the obfuscator to latest android-ndk library?

### ISSUE THREAD

**Issue by wustwg** [obfuscator-llvm/obfuscator#51]
hi,I want to apply the obfuscator to latest ndk ,but i cann't find demo from the google,the version of what ndk they use almost is below ndk-12b.ndk-12b is different from the lower version and it doesn't have the llvm-3.5 or arm-linux-androidarmeabi-clang3.4 directory,it only has a llvm directory.Besides,the ndk-12b's clang version is 3.8 , so how can i  config the ndk ???
by the way,I'm not good at english ...thanks !

**Comment by wangzh7678** [comment]
`android-ndk-r11c/build/core/toolchains`

**Comment by wustwg** [comment]
thansk.but  how can i use -xsa flag?I use the version is 3.4,but it doesn't works

**Comment by cryptopathe** [comment]
The -xse flag is not included in the open-source version, only in the commercial one (cf. https://strong.codes).

**Comment by yag00** [comment]
You can use my fork https://github.com/yag00/obfuscator. There is the xse
implementation!
