### ISSUE TITLE
How to generate a alloca Instruction for llvm IR

### ISSUE THREAD

**Issue by wangzh7678** [obfuscator-llvm/obfuscator#52]

**Comment by jowehrli** [comment]
Hi,

For the question llvm-related, I advise you to go to the mailing list:
http://lists.llvm.org/mailman/listinfo/llvm-dev

or the following tutorial: http://llvm.org/docs/WritingAnLLVMPass.html

Greetings,

Wehrli Johan

2016-08-25 13:44 GMT+02:00 wangzh7678 <notifications@github.com>:
