### ISSUE TITLE
report a bug.

### ISSUE THREAD

**Issue by wustwg** [obfuscator-llvm/obfuscator#53]
my system is:ubuntu 16,ndk 10b,obfucator 3.4
when i build the x86 abi,it doesn't work.It has cost my one day to find the reason: the same cmd to ndk's clang and obfuscator's,obfuscator's clang show " Selected gcc installation: ",just this.it seems that the obf-clang cang't find the x86's gcc.But I has printed the clang's args ,there are " -gcc-toolchain /....." ,besides these cmd work on ndk's clang.
can you tell me is this is a bug or my config fault?
if you dont have time to fix it ,can you tell me where can i reedit to fix the problem?
buy the way ,the "-xse " also doesn't work on my project, the obfucator version is 3.4
thank you very much.

**Comment by cryptopathe** [comment]
Concerning the "-xse" flag, it is not included in the open-source version, only in the commercial one (cf. https://strong.codes).

**Comment by wustwg** [comment]
oh .....thanks.
