### ISSUE TITLE
clang: error: -mllvm is not supported with -fembed-bitcode

### ISSUE THREAD

**Issue by crystalztl** [obfuscator-llvm/obfuscator#55]
clang: error: -mllvm is not supported with -fembed-bitcode

**Comment by jowehrli** [comment]
The -fembed-bitcode parameter is only supported in clang 3.9.

You just need to write -fembed-bitcode without the -mllvm.

You need to disable the bitcode creation in Xcode.

Meilleures salutations,

Wehrli Johan

2016-09-29 11:22 GMT+02:00 Tianli Zhang <notifications@github.com>:

**Comment by crystalztl** [comment]
Thanks for quick reply. 
In my project I need the bitcode feature for watchOS. currently my clang version is 3.7. so I need upgrade it to 3.9. Thanks
