### ISSUE TITLE
sudo vim Obfuscator\ 3.6.1.strings

### ISSUE THREAD

**Issue by lzyroot** [obfuscator-llvm/obfuscator#63]
bplist00ß^Q^BX^@^A^@^B^@^C^@^D^@^E^@^F^@^G^@^H^@        ^@
^@^K^@^L^@^M^@^N^@^O^@^P^@^Q^@^R^@^S^@^T^@^U^@^V^@^W^@^X^@^Y^@^Z^@^[^@^\^@^]^@^^^@^_^@ ^@!^@"^@#^@$^@%^@&^@'^@(^@)^@*^@+^@,^@-^@.^@/^@0^@1^@2^@3^@4^@5^@6^@7^@8^@9^@:^@;^@<^@=^@>^@?^@@^@A^@B^@C^@D^@E^@F^@G^@H^@I^@J^@K^@L^@M^@N^@O^@P^@Q^@R^@S^@T^@U^@V^@W^@X^@Y^@Z^@[^@\^@]^@^^@_^@`^@a^@b^@c^@d^@e^@f^@g^@h^@i^@j^@k^@l^@m^@n^@o^@p^@q^@r^@s^@t^@u^@v^@w^@x^@y^@z^@{^@|^@}^@~^@^?^@<80>^@<81>^@<82>^@<83>^@<84>^@<85>^@<86>^@<87>^@<88>^@<89>^@<8a>^@<8b>^@<8c>^@<8d>^@<8e>^@<8f>^@<90>^@<91>^@<92>^@<93>^@<94>^@<95>^@<96>^@<97>^@<98>^@<99>^@<9a>^@<9b>^@<9c>^@<9d>^@<9e>^@<9f>^@ ^@¡^@¢^@£^@¤^@¥^@¦^@§^@¨^@©^@ª^@«^@¬^@­^@®^@¯^@°^@±^@²^@³^@´^@µ^@¶^@·^@¸^@¹^@º^@»^@¼^@½^@¾^@¿^@À^@Á^@Â^@Ã^@Ä^@Å^@Æ^@Ç^@È^@É^@Ê^@Ë^@Ì^@Í^@Î^@Ï^@Ð^@Ñ^@Ò^@Ó^@Ô^@Õ^@Ö^@×^@Ø^@Ù^@Ú^@Û^@Ü^@Ý^@Þ^@ß^@à^@á^@â^@ã^@ä^@å^@æ^@ç^@è^@é^@ê^@ë^@ì^@í^@î^@ï^@ð^@ñ^@ò^@ó^@ô^@õ^@ö^@÷^@ø^@ù^@ú^@û^@ü^@ý^@þ^@ÿ^A^@^A^A^A^B^A^C^A^D^A^E^A^F^A^G^A^H^A     ^A
@                                                                               @                                                                               @                                                                               @                                                                               @                                                                               @                                                                               @                                                                               @                                                                               @                                                                               @                                                                               @
:wq

**Comment by pjunodsc** [comment]
You might want to first convert this file to XML thanks to` plutil -convert xml1 "Obfuscator 3.6.1.strings"`, edit it, and then convert it back to binary thanks to `plutil -convert binary1   "Obfuscator 3.6.1.strings"`.

**Comment by cryptopathe** [comment]
First, you might want to convert the file in XML thanks to `plutil -convert xml1 "Obfuscator 3.6.1.strings"`, then edit it, and eventually convert it back to binary `plutil -convert binary1 "Obfuscator 3.6.1.strings"`.
