### ISSUE TITLE
Cannot built on Windows

### ISSUE THREAD

**Issue by beraphin** [obfuscator-llvm/obfuscator#64]
recently I download obfuscator-llvm project on github and I built it as what this artical said:
http://llvm.org/docs/GettingStartedVS.html
my os is Win10-64bit with VS2015
here is what I did:
1.installed python , pip and cmake
2.installed GnuWin32 (I'm sure it's well installed as I can use Linux command in cmd.exe)
3.Unzipped obfuscator-llvm-3.6.1.zip ,then I created a directory named "mybuilddir"(not in the source      
   code directory)
4.In mybuilddir directory,I ran following commands:
          cmake path-to-obfuscator-llvm-3.6.1
          cmake --build .
          cmake --build . --target install
5.after aboving steps,I got these errors:

  D:\obfuscator-llvm-3.6.1\tools\clang\lib\Serialization\ASTWriter.cpp(1517): e
rror C2664: 'void llvm::BitstreamWriter::EmitRecordWithBlob<uint64_t>(unsigned
int,llvm::SmallVectorImpl<uint64_t> &,llvm::StringRef)': cannot convert argumen
t 3 from 'uint32_t *' to 'llvm::StringRef' [D:\mybuilddir\tools\clang\lib\Seria
lization\clangSerialization.vcxproj]
  D:\obfuscator-llvm-3.6.1\tools\clang\lib\Serialization\ASTWriter.cpp(1912): e
rror C2664: 'void llvm::BitstreamWriter::EmitRecordWithBlob<uint64_t>(unsigned
int,llvm::SmallVectorImpl<uint64_t> &,llvm::StringRef)': cannot convert argumen
t 3 from 'uint32_t *' to 'llvm::StringRef' [D:\mybuilddir\tools\clang\lib\Seria
lization\clangSerialization.vcxproj]
  D:\obfuscator-llvm-3.6.1\tools\clang\lib\Serialization\ASTWriter.cpp(2237): e
rror C2664: 'void llvm::BitstreamWriter::EmitRecordWithBlob<uint64_t>(unsigned
int,llvm::SmallVectorImpl<uint64_t> &,llvm::StringRef)': cannot convert argumen
t 3 from 'uint32_t *' to 'llvm::StringRef' [D:\mybuilddir\tools\clang\lib\Seria
lization\clangSerialization.vcxproj]
  D:\obfuscator-llvm-3.6.1\tools\clang\lib\Serialization\ASTWriter.cpp(2783): e
rror C2664: 'void llvm::BitstreamWriter::EmitRecordWithBlob<uint64_t>(unsigned
int,llvm::SmallVectorImpl<uint64_t> &,llvm::StringRef)': cannot convert argumen
t 3 from 'std::pair<uint32_t,clang::serialization::DeclID> *' to 'llvm::StringR
ef' [D:\mybuilddir\tools\clang\lib\Serialization\clangSerialization.vcxproj]
  D:\obfuscator-llvm-3.6.1\tools\clang\lib\Serialization\ASTWriter.cpp(2802): e
rror C2664: 'void llvm::BitstreamWriter::EmitRecordWithBlob<uint64_t>(unsigned
int,llvm::SmallVectorImpl<uint64_t> &,llvm::StringRef)': cannot convert argumen
t 3 from 'uint32_t *' to 'llvm::StringRef' [D:\mybuilddir\tools\clang\lib\Seria
lization\clangSerialization.vcxproj]
  D:\obfuscator-llvm-3.6.1\tools\clang\lib\Serialization\ASTWriter.cpp(2815): e
rror C2664: 'void llvm::BitstreamWriter::EmitRecordWithBlob<uint64_t>(unsigned
int,llvm::SmallVectorImpl<uint64_t> &,llvm::StringRef)': cannot convert argumen
t 3 from 'clang::serialization::DeclOffset *' to 'llvm::StringRef' [D:\mybuildd
ir\tools\clang\lib\Serialization\clangSerialization.vcxproj]
  D:\obfuscator-llvm-3.6.1\tools\clang\lib\Serialization\ASTWriter.cpp(3070): e
rror C2664: 'void llvm::BitstreamWriter::EmitRecordWithBlob<uint64_t>(unsigned
int,llvm::SmallVectorImpl<uint64_t> &,llvm::StringRef)': cannot convert argumen
t 3 from 'uint32_t *' to 'llvm::StringRef' [D:\mybuilddir\tools\clang\lib\Seria
lization\clangSerialization.vcxproj]
  D:\obfuscator-llvm-3.6.1\tools\clang\lib\Serialization\ASTWriter.cpp(3520): e
rror C2664: 'void llvm::BitstreamWriter::EmitRecordWithBlob<uint64_t>(unsigned
int,llvm::SmallVectorImpl<uint64_t> &,llvm::StringRef)': cannot convert argumen
t 3 from 'uint32_t *' to 'llvm::StringRef' [D:\mybuilddir\tools\clang\lib\Seria
lization\clangSerialization.vcxproj]
  D:\obfuscator-llvm-3.6.1\tools\clang\lib\Serialization\ASTWriter.cpp(4446): e
rror C2664: 'void llvm::BitstreamWriter::EmitRecordWithBlob<uint64_t>(unsigned
int,llvm::SmallVectorImpl<uint64_t> &,llvm::StringRef)': cannot convert argumen
t 3 from 'std::pair<uint32_t,clang::serialization::DeclID> *' to 'llvm::StringR
ef' [D:\mybuilddir\tools\clang\lib\Serialization\clangSerialization.vcxproj]

9 errors in total.
I have no idea why I got these errors 
help me pls

**Comment by karliwson** [comment]
I've had a hard time trying to build it on Windows, but with some work I finally did.

Check out https://github.com/karliwson/obfuscator/tree/llvm-3.7.1-win
I'll try to do the same for LLVM 4.0.

Please note that the fixes I did are not fully tested. You should test it yourself.
