### ISSUE TITLE
can't build arm64-v8a,

### ISSUE THREAD

**Issue by BiteFoo** [obfuscator-llvm/obfuscator#65]
When I built arm64-v8a by 3.6.1 and ndk r11c ,but I got an error that  permission denied ,just like this "[arm64-v8a] Compile        : demo2 <= demo2.c
make: execvp: /home/cat/Documents/ndk/android-ndk-r11c/toolchains/obfuscator-llvm: Permission denied
"  ,what should I do

**Comment by obfuscator-llvm** [comment]
Fix the permissions of the O-LLVM binary ?
