### ISSUE TITLE
Can o-llvm cross-compile for windows ?

### ISSUE THREAD

**Issue by beraphin** [obfuscator-llvm/obfuscator#67]
I built ollvm on Linux and I want to obfuscate control flow of windows exe file,
howerver,when I set flag --windows-msvc，I got this output:
unsupported option '--windows-msvc'

So I am wondering if it's possible to cross-compile for windows?

**Comment by obfuscator-llvm** [comment]
Yes it is possible, modulo the limitations of vanilla LLVM on that platform.
