### ISSUE TITLE
How can I obscure the specified function when use ndk-build to compile DLL？

### ISSUE THREAD

**Issue by Igamegum** [obfuscator-llvm/obfuscator#68]
Recently，I use obscure-llvm to obscure my dynamic link library.
I add such sentence in _Android.mk_

`LOCAL_CFLAGS := -mllvm -sub -mllvm -fla -mllvm -bcf `

And my Application.mk as below 

`APP_PLATFORM := android-14
APP_ABI :=  armeabi-v7a  
APP_STL :=gnustl_static
NDK_TOOLCHAIN_VERSION := clang3.6-obfuscator
APP_CPPFLAGS += -std=c++11 `

As a result,It  seems that all the funcrion has been obscured,so my apk run 4-5times slower ，I do not  what happend ，so I hope your help, thanks!

**Comment by obfuscator-llvm** [comment]
You can put the function you would like to protect in an isolated module (i.e., a `.c` file) and apply protection flags to this module only.
