### ISSUE TITLE
4.0.1 -bcf crash when building AFNetworking.

### ISSUE THREAD

**Issue by Dendim0n** [obfuscator-llvm/obfuscator#72]
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata i8** %self.addralteredBB, metadata !483, metadata !453), !dbg !463
label %originalBBalteredBB
i8* (i8*, i8*)* @"\01+[AFNetworkActivityIndicatorManager sharedManager]"
!483 = !DILocalVariable(name: "self", arg: 1, scope: !484, type: !462, flags: DIFlagArtificial | DIFlagObjectPointer)
!484 = distinct !DISubprogram(name: "+[AFNetworkActivityIndicatorManager sharedManager]", scope: !3, file: !3, line: 60, type: !4, isLocal: true, isDefinition: true, scopeLine: 60, flags: DIFlagPrototyped, isOptimized: false, unit: !485, variables: !418)
!463 = !DILocation(line: 0, scope: !2)
!2 = distinct !DISubprogram(name: "+[AFNetworkActivityIndicatorManager sharedManager]", scope: !3, file: !3, line: 60, type: !4, isLocal: true, isDefinition: true, scopeLine: 60, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata i8** %_cmd.addralteredBB, metadata !500, metadata !453), !dbg !463
label %originalBBalteredBB
i8* (i8*, i8*)* @"\01+[AFNetworkActivityIndicatorManager sharedManager]"
!500 = !DILocalVariable(name: "_cmd", arg: 2, scope: !484, type: !465, flags: DIFlagArtificial)
!484 = distinct !DISubprogram(name: "+[AFNetworkActivityIndicatorManager sharedManager]", scope: !3, file: !3, line: 60, type: !4, isLocal: true, isDefinition: true, scopeLine: 60, flags: DIFlagPrototyped, isOptimized: false, unit: !485, variables: !418)
!463 = !DILocation(line: 0, scope: !2)
!2 = distinct !DISubprogram(name: "+[AFNetworkActivityIndicatorManager sharedManager]", scope: !3, file: !3, line: 60, type: !4, isLocal: true, isDefinition: true, scopeLine: 60, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata %0** %self.addralteredBB, metadata !751, metadata !453), !dbg !734
label %originalBBalteredBB
void (%0*, i8*)* @"\01-[AFNetworkActivityIndicatorManager updateNetworkActivityIndicatorVisibility]"
!751 = !DILocalVariable(name: "self", arg: 1, scope: !752, type: !637, flags: DIFlagArtificial | DIFlagObjectPointer)
!752 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager updateNetworkActivityIndicatorVisibility]", scope: !3, file: !3, line: 115, type: !633, isLocal: true, isDefinition: true, scopeLine: 115, flags: DIFlagPrototyped, isOptimized: false, unit: !753, variables: !418)
!734 = !DILocation(line: 0, scope: !732)
!732 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager updateNetworkActivityIndicatorVisibility]", scope: !3, file: !3, line: 115, type: !633, isLocal: true, isDefinition: true, scopeLine: 115, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata i8** %_cmd.addralteredBB, metadata !769, metadata !453), !dbg !734
label %originalBBalteredBB
void (%0*, i8*)* @"\01-[AFNetworkActivityIndicatorManager updateNetworkActivityIndicatorVisibility]"
!769 = !DILocalVariable(name: "_cmd", arg: 2, scope: !752, type: !465, flags: DIFlagArtificial)
!752 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager updateNetworkActivityIndicatorVisibility]", scope: !3, file: !3, line: 115, type: !633, isLocal: true, isDefinition: true, scopeLine: 115, flags: DIFlagPrototyped, isOptimized: false, unit: !753, variables: !418)
!734 = !DILocation(line: 0, scope: !732)
!732 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager updateNetworkActivityIndicatorVisibility]", scope: !3, file: !3, line: 115, type: !633, isLocal: true, isDefinition: true, scopeLine: 115, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata i8** %.addralteredBB, metadata !834, metadata !453), !dbg !832
label %originalBBalteredBB
void (i8*)* @__destroy_helper_block_.54
!834 = !DILocalVariable(arg: 1, scope: !835, type: !128, flags: DIFlagArtificial | DIFlagObjectPointer)
!835 = distinct !DISubprogram(name: "__destroy_helper_block_", scope: !3, file: !3, line: 126, type: !512, isLocal: true, isDefinition: true, scopeLine: 126, isOptimized: false, unit: !836, variables: !418)
!832 = !DILocation(line: 0, scope: !830)
!830 = distinct !DISubprogram(name: "__destroy_helper_block_", scope: !3, file: !3, line: 126, type: !512, isLocal: true, isDefinition: true, scopeLine: 126, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.value variable and !dbg attachment
  call void @llvm.dbg.value(metadata i8* %20, i64 0, metadata !903, metadata !453), !dbg !896
label %originalBBalteredBB
void (i8*)* @"__59-[AFNetworkActivityIndicatorManager incrementActivityCount]_block_invoke"
!903 = !DILocalVariable(name: ".block_descriptor", arg: 1, scope: !904, file: !3, line: 136, type: !921, flags: DIFlagArtificial)
!904 = distinct !DISubprogram(name: "__59-[AFNetworkActivityIndicatorManager incrementActivityCount]_block_invoke", scope: !3, file: !3, line: 136, type: !512, isLocal: true, isDefinition: true, scopeLine: 136, flags: DIFlagPrototyped, isOptimized: false, unit: !905, variables: !418)
!896 = !DILocation(line: 136, column: 47, scope: !885)
!885 = distinct !DISubprogram(name: "__59-[AFNetworkActivityIndicatorManager incrementActivityCount]_block_invoke", scope: !3, file: !3, line: 136, type: !512, isLocal: true, isDefinition: true, scopeLine: 136, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata !418, metadata !903, metadata !453), !dbg !896
label %originalBBalteredBB
void (i8*)* @"__59-[AFNetworkActivityIndicatorManager incrementActivityCount]_block_invoke"
!903 = !DILocalVariable(name: ".block_descriptor", arg: 1, scope: !904, file: !3, line: 136, type: !921, flags: DIFlagArtificial)
!904 = distinct !DISubprogram(name: "__59-[AFNetworkActivityIndicatorManager incrementActivityCount]_block_invoke", scope: !3, file: !3, line: 136, type: !512, isLocal: true, isDefinition: true, scopeLine: 136, flags: DIFlagPrototyped, isOptimized: false, unit: !905, variables: !418)
!896 = !DILocation(line: 136, column: 47, scope: !885)
!885 = distinct !DISubprogram(name: "__59-[AFNetworkActivityIndicatorManager incrementActivityCount]_block_invoke", scope: !3, file: !3, line: 136, type: !512, isLocal: true, isDefinition: true, scopeLine: 136, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata <{ i8*, i32, i32, i8*, %struct.__block_descriptor*, %0* }>** %block.addralteredBB, metadata !932, metadata !535), !dbg !899
label %originalBBalteredBB
void (i8*)* @"__59-[AFNetworkActivityIndicatorManager incrementActivityCount]_block_invoke"
!932 = !DILocalVariable(name: "self", scope: !904, file: !3, line: 138, type: !635)
!904 = distinct !DISubprogram(name: "__59-[AFNetworkActivityIndicatorManager incrementActivityCount]_block_invoke", scope: !3, file: !3, line: 136, type: !512, isLocal: true, isDefinition: true, scopeLine: 136, flags: DIFlagPrototyped, isOptimized: false, unit: !905, variables: !418)
!899 = !DILocation(line: 138, column: 5, scope: !885)
!885 = distinct !DISubprogram(name: "__59-[AFNetworkActivityIndicatorManager incrementActivityCount]_block_invoke", scope: !3, file: !3, line: 136, type: !512, isLocal: true, isDefinition: true, scopeLine: 136, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata i8** %.addralteredBB, metadata !942, metadata !453), !dbg !940
label %originalBBalteredBB
void (i8*)* @__destroy_helper_block_.61
!942 = !DILocalVariable(arg: 1, scope: !943, type: !128, flags: DIFlagArtificial | DIFlagObjectPointer)
!943 = distinct !DISubprogram(name: "__destroy_helper_block_", scope: !3, file: !3, line: 138, type: !512, isLocal: true, isDefinition: true, scopeLine: 138, isOptimized: false, unit: !944, variables: !418)
!940 = !DILocation(line: 0, scope: !938)
!938 = distinct !DISubprogram(name: "__destroy_helper_block_", scope: !3, file: !3, line: 138, type: !512, isLocal: true, isDefinition: true, scopeLine: 138, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.value variable and !dbg attachment
  call void @llvm.dbg.value(metadata i8* %20, i64 0, metadata !1023, metadata !453), !dbg !1016
label %originalBBalteredBB
void (i8*)* @"__59-[AFNetworkActivityIndicatorManager decrementActivityCount]_block_invoke"
!1023 = !DILocalVariable(name: ".block_descriptor", arg: 1, scope: !1024, file: !3, line: 151, type: !1041, flags: DIFlagArtificial)
!1024 = distinct !DISubprogram(name: "__59-[AFNetworkActivityIndicatorManager decrementActivityCount]_block_invoke", scope: !3, file: !3, line: 151, type: !512, isLocal: true, isDefinition: true, scopeLine: 151, flags: DIFlagPrototyped, isOptimized: false, unit: !1025, variables: !418)
!1016 = !DILocation(line: 151, column: 47, scope: !1005)
!1005 = distinct !DISubprogram(name: "__59-[AFNetworkActivityIndicatorManager decrementActivityCount]_block_invoke", scope: !3, file: !3, line: 151, type: !512, isLocal: true, isDefinition: true, scopeLine: 151, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata !418, metadata !1023, metadata !453), !dbg !1016
label %originalBBalteredBB
void (i8*)* @"__59-[AFNetworkActivityIndicatorManager decrementActivityCount]_block_invoke"
!1023 = !DILocalVariable(name: ".block_descriptor", arg: 1, scope: !1024, file: !3, line: 151, type: !1041, flags: DIFlagArtificial)
!1024 = distinct !DISubprogram(name: "__59-[AFNetworkActivityIndicatorManager decrementActivityCount]_block_invoke", scope: !3, file: !3, line: 151, type: !512, isLocal: true, isDefinition: true, scopeLine: 151, flags: DIFlagPrototyped, isOptimized: false, unit: !1025, variables: !418)
!1016 = !DILocation(line: 151, column: 47, scope: !1005)
!1005 = distinct !DISubprogram(name: "__59-[AFNetworkActivityIndicatorManager decrementActivityCount]_block_invoke", scope: !3, file: !3, line: 151, type: !512, isLocal: true, isDefinition: true, scopeLine: 151, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata <{ i8*, i32, i32, i8*, %struct.__block_descriptor*, %0* }>** %block.addralteredBB, metadata !1052, metadata !535), !dbg !1019
label %originalBBalteredBB
void (i8*)* @"__59-[AFNetworkActivityIndicatorManager decrementActivityCount]_block_invoke"
!1052 = !DILocalVariable(name: "self", scope: !1024, file: !3, line: 153, type: !635)
!1024 = distinct !DISubprogram(name: "__59-[AFNetworkActivityIndicatorManager decrementActivityCount]_block_invoke", scope: !3, file: !3, line: 151, type: !512, isLocal: true, isDefinition: true, scopeLine: 151, flags: DIFlagPrototyped, isOptimized: false, unit: !1025, variables: !418)
!1019 = !DILocation(line: 153, column: 5, scope: !1005)
!1005 = distinct !DISubprogram(name: "__59-[AFNetworkActivityIndicatorManager decrementActivityCount]_block_invoke", scope: !3, file: !3, line: 151, type: !512, isLocal: true, isDefinition: true, scopeLine: 151, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata %0** %self.addralteredBB, metadata !1102, metadata !453), !dbg !1074
label %originalBBalteredBB
void (%0*, i8*, %9*)* @"\01-[AFNetworkActivityIndicatorManager networkRequestDidStart:]"
!1102 = !DILocalVariable(name: "self", arg: 1, scope: !1103, type: !637, flags: DIFlagArtificial | DIFlagObjectPointer)
!1103 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager networkRequestDidStart:]", scope: !3, file: !3, line: 156, type: !1063, isLocal: true, isDefinition: true, scopeLine: 156, flags: DIFlagPrototyped, isOptimized: false, unit: !1104, variables: !418)
!1074 = !DILocation(line: 0, scope: !1062)
!1062 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager networkRequestDidStart:]", scope: !3, file: !3, line: 156, type: !1063, isLocal: true, isDefinition: true, scopeLine: 156, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata i8** %_cmd.addralteredBB, metadata !1120, metadata !453), !dbg !1074
label %originalBBalteredBB
void (%0*, i8*, %9*)* @"\01-[AFNetworkActivityIndicatorManager networkRequestDidStart:]"
!1120 = !DILocalVariable(name: "_cmd", arg: 2, scope: !1103, type: !465, flags: DIFlagArtificial)
!1103 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager networkRequestDidStart:]", scope: !3, file: !3, line: 156, type: !1063, isLocal: true, isDefinition: true, scopeLine: 156, flags: DIFlagPrototyped, isOptimized: false, unit: !1104, variables: !418)
!1074 = !DILocation(line: 0, scope: !1062)
!1062 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager networkRequestDidStart:]", scope: !3, file: !3, line: 156, type: !1063, isLocal: true, isDefinition: true, scopeLine: 156, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata %9** %notification.addralteredBB, metadata !1121, metadata !453), !dbg !1077
label %originalBBalteredBB
void (%0*, i8*, %9*)* @"\01-[AFNetworkActivityIndicatorManager networkRequestDidStart:]"
!1121 = !DILocalVariable(name: "notification", arg: 3, scope: !1103, file: !3, line: 156, type: !1065)
!1103 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager networkRequestDidStart:]", scope: !3, file: !3, line: 156, type: !1063, isLocal: true, isDefinition: true, scopeLine: 156, flags: DIFlagPrototyped, isOptimized: false, unit: !1104, variables: !418)
!1077 = !DILocation(line: 156, column: 50, scope: !1062)
!1062 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager networkRequestDidStart:]", scope: !3, file: !3, line: 156, type: !1063, isLocal: true, isDefinition: true, scopeLine: 156, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata %9** %notification.addralteredBB, metadata !1197, metadata !453), !dbg !1126
label %originalBBalteredBB
%10* (%9*)* @AFNetworkRequestFromNotification
!1197 = !DILocalVariable(name: "notification", arg: 1, scope: !1198, file: !3, line: 34, type: !1065)
!1198 = distinct !DISubprogram(name: "AFNetworkRequestFromNotification", scope: !3, file: !3, line: 34, type: !1123, isLocal: true, isDefinition: true, scopeLine: 34, flags: DIFlagPrototyped, isOptimized: false, unit: !1199, variables: !418)
!1126 = !DILocation(line: 34, column: 72, scope: !1122)
!1122 = distinct !DISubprogram(name: "AFNetworkRequestFromNotification", scope: !3, file: !3, line: 34, type: !1123, isLocal: true, isDefinition: true, scopeLine: 34, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata %0** %self.addralteredBB, metadata !1245, metadata !453), !dbg !1217
label %originalBBalteredBB
void (%0*, i8*, %9*)* @"\01-[AFNetworkActivityIndicatorManager networkRequestDidFinish:]"
!1245 = !DILocalVariable(name: "self", arg: 1, scope: !1246, type: !637, flags: DIFlagArtificial | DIFlagObjectPointer)
!1246 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager networkRequestDidFinish:]", scope: !3, file: !3, line: 162, type: !1063, isLocal: true, isDefinition: true, scopeLine: 162, flags: DIFlagPrototyped, isOptimized: false, unit: !1247, variables: !418)
!1217 = !DILocation(line: 0, scope: !1215)
!1215 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager networkRequestDidFinish:]", scope: !3, file: !3, line: 162, type: !1063, isLocal: true, isDefinition: true, scopeLine: 162, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata i8** %_cmd.addralteredBB, metadata !1263, metadata !453), !dbg !1217
label %originalBBalteredBB
void (%0*, i8*, %9*)* @"\01-[AFNetworkActivityIndicatorManager networkRequestDidFinish:]"
!1263 = !DILocalVariable(name: "_cmd", arg: 2, scope: !1246, type: !465, flags: DIFlagArtificial)
!1246 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager networkRequestDidFinish:]", scope: !3, file: !3, line: 162, type: !1063, isLocal: true, isDefinition: true, scopeLine: 162, flags: DIFlagPrototyped, isOptimized: false, unit: !1247, variables: !418)
!1217 = !DILocation(line: 0, scope: !1215)
!1215 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager networkRequestDidFinish:]", scope: !3, file: !3, line: 162, type: !1063, isLocal: true, isDefinition: true, scopeLine: 162, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata %9** %notification.addralteredBB, metadata !1264, metadata !453), !dbg !1220
label %originalBBalteredBB
void (%0*, i8*, %9*)* @"\01-[AFNetworkActivityIndicatorManager networkRequestDidFinish:]"
!1264 = !DILocalVariable(name: "notification", arg: 3, scope: !1246, file: !3, line: 162, type: !1065)
!1246 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager networkRequestDidFinish:]", scope: !3, file: !3, line: 162, type: !1063, isLocal: true, isDefinition: true, scopeLine: 162, flags: DIFlagPrototyped, isOptimized: false, unit: !1247, variables: !418)
!1220 = !DILocation(line: 162, column: 51, scope: !1215)
!1215 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager networkRequestDidFinish:]", scope: !3, file: !3, line: 162, type: !1063, isLocal: true, isDefinition: true, scopeLine: 162, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata %0** %self.addralteredBB, metadata !1270, metadata !453), !dbg !1267
label %originalBBalteredBB
i8 (%0*, i8*)* @"\01-[AFNetworkActivityIndicatorManager isEnabled]"
!1270 = !DILocalVariable(name: "self", arg: 1, scope: !1271, type: !637, flags: DIFlagArtificial | DIFlagObjectPointer)
!1271 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager isEnabled]", scope: !370, file: !370, line: 52, type: !723, isLocal: true, isDefinition: true, scopeLine: 52, flags: DIFlagArtificial | DIFlagPrototyped, isOptimized: false, unit: !1272, variables: !418)
!1267 = !DILocation(line: 0, scope: !1265)
!1265 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager isEnabled]", scope: !370, file: !370, line: 52, type: !723, isLocal: true, isDefinition: true, scopeLine: 52, flags: DIFlagArtificial | DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata i8** %_cmd.addralteredBB, metadata !1288, metadata !453), !dbg !1267
label %originalBBalteredBB
i8 (%0*, i8*)* @"\01-[AFNetworkActivityIndicatorManager isEnabled]"
!1288 = !DILocalVariable(name: "_cmd", arg: 2, scope: !1271, type: !465, flags: DIFlagArtificial)
!1271 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager isEnabled]", scope: !370, file: !370, line: 52, type: !723, isLocal: true, isDefinition: true, scopeLine: 52, flags: DIFlagArtificial | DIFlagPrototyped, isOptimized: false, unit: !1272, variables: !418)
!1267 = !DILocation(line: 0, scope: !1265)
!1265 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager isEnabled]", scope: !370, file: !370, line: 52, type: !723, isLocal: true, isDefinition: true, scopeLine: 52, flags: DIFlagArtificial | DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata %0** %self.addralteredBB, metadata !1319, metadata !453), !dbg !1315
label %originalBBalteredBB
void (%0*, i8*, %4*)* @"\01-[AFNetworkActivityIndicatorManager setActivityIndicatorVisibilityTimer:]"
!1319 = !DILocalVariable(name: "self", arg: 1, scope: !1320, type: !637, flags: DIFlagArtificial | DIFlagObjectPointer)
!1320 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager setActivityIndicatorVisibilityTimer:]", scope: !3, file: !3, line: 50, type: !1312, isLocal: true, isDefinition: true, scopeLine: 50, flags: DIFlagArtificial | DIFlagPrototyped, isOptimized: false, unit: !1321, variables: !418)
!1315 = !DILocation(line: 0, scope: !1311)
!1311 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager setActivityIndicatorVisibilityTimer:]", scope: !3, file: !3, line: 50, type: !1312, isLocal: true, isDefinition: true, scopeLine: 50, flags: DIFlagArtificial | DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata i8** %_cmd.addralteredBB, metadata !1337, metadata !453), !dbg !1315
label %originalBBalteredBB
void (%0*, i8*, %4*)* @"\01-[AFNetworkActivityIndicatorManager setActivityIndicatorVisibilityTimer:]"
!1337 = !DILocalVariable(name: "_cmd", arg: 2, scope: !1320, type: !465, flags: DIFlagArtificial)
!1320 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager setActivityIndicatorVisibilityTimer:]", scope: !3, file: !3, line: 50, type: !1312, isLocal: true, isDefinition: true, scopeLine: 50, flags: DIFlagArtificial | DIFlagPrototyped, isOptimized: false, unit: !1321, variables: !418)
!1315 = !DILocation(line: 0, scope: !1311)
!1311 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager setActivityIndicatorVisibilityTimer:]", scope: !3, file: !3, line: 50, type: !1312, isLocal: true, isDefinition: true, scopeLine: 50, flags: DIFlagArtificial | DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata %4** %activityIndicatorVisibilityTimer.addralteredBB, metadata !1338, metadata !453), !dbg !1315
label %originalBBalteredBB
void (%0*, i8*, %4*)* @"\01-[AFNetworkActivityIndicatorManager setActivityIndicatorVisibilityTimer:]"
!1338 = !DILocalVariable(name: "activityIndicatorVisibilityTimer", arg: 3, scope: !1320, type: !375)
!1320 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager setActivityIndicatorVisibilityTimer:]", scope: !3, file: !3, line: 50, type: !1312, isLocal: true, isDefinition: true, scopeLine: 50, flags: DIFlagArtificial | DIFlagPrototyped, isOptimized: false, unit: !1321, variables: !418)
!1315 = !DILocation(line: 0, scope: !1311)
!1311 = distinct !DISubprogram(name: "-[AFNetworkActivityIndicatorManager setActivityIndicatorVisibilityTimer:]", scope: !3, file: !3, line: 50, type: !1312, isLocal: true, isDefinition: true, scopeLine: 50, flags: DIFlagArtificial | DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata i8** %self.addralteredBB, metadata !483, metadata !453), !dbg !463
label %originalBBalteredBB
i8* (i8*, i8*)* @"\01+[AFNetworkActivityIndicatorManager sharedManager]"
!483 = !DILocalVariable(name: "self", arg: 1, scope: !484, type: !462, flags: DIFlagArtificial | DIFlagObjectPointer)
!484 = distinct !DISubprogram(name: "+[AFNetworkActivityIndicatorManager sharedManager]", scope: !3, file: !3, line: 60, type: !4, isLocal: true, isDefinition: true, scopeLine: 60, flags: DIFlagPrototyped, isOptimized: false, unit: !485, variables: !418)
!463 = !DILocation(line: 0, scope: !2)
!2 = distinct !DISubprogram(name: "+[AFNetworkActivityIndicatorManager sharedManager]", scope: !3, file: !3, line: 60, type: !4, isLocal: true, isDefinition: true, scopeLine: 60, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
mismatched subprogram between llvm.dbg.declare variable and !dbg attachment
  call void @llvm.dbg.declare(metadata i8** %_cmd.addralteredBB, metadata !500, metadata !453), !dbg !463
label %originalBBalteredBB
i8* (i8*, i8*)* @"\01+[AFNetworkActivityIndicatorManager sharedManager]"
!500 = !DILocalVariable(name: "_cmd", arg: 2, scope: !484, type: !465, flags: DIFlagArtificial)
!484 = distinct !DISubprogram(name: "+[AFNetworkActivityIndicatorManager sharedManager]", scope: !3, file: !3, line: 60, type: !4, isLocal: true, isDefinition: true, scopeLine: 60, flags: DIFlagPrototyped, isOptimized: false, unit: !485, variables: !418)
!463 = !DILocation(line: 0, scope: !2)
!2 = distinct !DISubprogram(name: "+[AFNetworkActivityIndicatorManager sharedManager]", scope: !3, file: !3, line: 60, type: !4, isLocal: true, isDefinition: true, scopeLine: 60, flags: DIFlagPrototyped, isOptimized: false, unit: !19, variables: !418)
Assertion failed: (DI->getVariable()->isValidLocationForIntrinsic(DbgLoc) && "Expected inlined-at fields to agree"), function selectIntrinsicCall, file /Users/renqiming/Documents/iOS/mtprotect_ios/lib/CodeGen/SelectionDAG/FastISel.cpp, line 1145.
0  clang-4.0                0x0000000108b7154c llvm::sys::PrintStackTrace(llvm::raw_ostream&) + 60
1  clang-4.0                0x0000000108b71ac9 PrintStackTraceSignalHandler(void*) + 25
2  clang-4.0                0x0000000108b6da49 llvm::sys::RunSignalHandlers() + 425
3  clang-4.0                0x0000000108b71e52 SignalHandler(int) + 354
4  libsystem_platform.dylib 0x00007fffd91abb3a _sigtramp + 26
5  libsystem_platform.dylib 0xffffffffd6099558 _sigtramp + 4243511864
6  libsystem_c.dylib        0x00007fffd9030420 abort + 129
7  libsystem_c.dylib        0x00007fffd8ff7893 basename_r + 0
8  clang-4.0                0x0000000109c8b251 llvm::FastISel::selectIntrinsicCall(llvm::IntrinsicInst const*) + 1297
9  clang-4.0                0x0000000109c8aca0 llvm::FastISel::selectCall(llvm::User const*) + 960
10 clang-4.0                0x0000000109c8428e llvm::FastISel::selectOperator(llvm::User const*, unsigned int) + 1102
11 clang-4.0                0x0000000109c8ccd7 llvm::FastISel::selectInstruction(llvm::Instruction const*) + 935
12 clang-4.0                0x0000000109e86f52 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) + 2770
13 clang-4.0                0x0000000109e84e9b llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) + 1643
14 clang-4.0                0x00000001067e7b1b (anonymous namespace)::ARMDAGToDAGISel::runOnMachineFunction(llvm::MachineFunction&) + 59
15 clang-4.0                0x0000000107c70c11 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) + 449
16 clang-4.0                0x0000000108112e1f llvm::FPPassManager::runOnFunction(llvm::Function&) + 399
17 clang-4.0                0x0000000108113325 llvm::FPPassManager::runOnModule(llvm::Module&) + 117
18 clang-4.0                0x00000001081140f4 (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) + 2196
19 clang-4.0                0x00000001081135e6 llvm::legacy::PassManagerImpl::run(llvm::Module&) + 342
20 clang-4.0                0x0000000108114e21 llvm::legacy::PassManager::run(llvm::Module&) + 33
21 clang-4.0                0x0000000108f408dc (anonymous namespace)::EmitAssemblyHelper::EmitAssembly(clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >) + 1804
22 clang-4.0                0x0000000108f3d703 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream> >) + 4227
23 clang-4.0                0x00000001092949ba clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) + 5226
24 clang-4.0                0x000000010aeabb06 clang::ParseAST(clang::Sema&, bool, bool) + 1238
25 clang-4.0                0x00000001099571d5 clang::ASTFrontendAction::ExecuteAction() + 485
26 clang-4.0                0x0000000109292b3a clang::CodeGenAction::ExecuteAction() + 7290
27 clang-4.0                0x00000001099561f0 clang::FrontendAction::Execute() + 112
28 clang-4.0                0x0000000109881626 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) + 2278
29 clang-4.0                0x00000001099f2825 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) + 6021
30 clang-4.0                0x00000001061db49a cc1_main(llvm::ArrayRef<char const*>, char const*, void*) + 4906
31 clang-4.0                0x00000001061cb46e ExecuteCC1Tool(llvm::ArrayRef<char const*>, llvm::StringRef) + 622
32 clang-4.0                0x00000001061c8699 main + 4457
33 libdyld.dylib            0x00007fffd8f9c235 start + 1
34 libdyld.dylib            0x0000000000000098 start + 654720612

1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/Users/renqiming/Documents/iOS/sakguard/SAKGuardTest/Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m'.
4.	Running pass 'ARM Instruction Selection' on function '@"\01+[AFNetworkActivityIndicatorManager sharedManager]"'
clang-4.0: error: unable to execute command: Abort trap: 6
clang-4.0: error: clang frontend command failed due to signal (use -v to see invocation)
Obfuscator-LLVM clang version 4.0.1  (based on Obfuscator-LLVM 4.0.1)

**Comment by fighting300** [comment]
@Dendim0n  how to solve this problem?

**Comment by Dendim0n** [comment]
@fighting300 not yet.. but it seems like only crash when compiling obj-c files.
