### ISSUE TITLE
fatal error: 'stdio.h' file not found

### ISSUE THREAD

**Issue by SanDiegoXu** [obfuscator-llvm/obfuscator#74]
Hello, I hava a problem when I use it by command line on my Macbook.

I just write a C program 'test.c', to printf 'hello,world'.  
My command is : 
`..../Software/obfuscator/bin/clang test.c -o test -mllvm -sub`
But get an error:
`fatal error: 'stdio.h' file not found`.

Then I search for solution, someone says the reason is lacking of "tools chain", but I can find the .h files in clang's directry.
So, how to solve the problem? Thank you.

**Comment by GavinPayne** [comment]
I have the same issue.
I build branch llvm-4.0 on my Macbook using cmake 3.9.0-rc5.
When generate makefile, It comes the warning "Policy CMP0068: RPATH setting on macOS do not affect".
But all make is OK.

**Comment by GavinPayne** [comment]
test "xcode-select –install"

**Comment by Dendim0n** [comment]
Try to recompile? Lacking STL header sometimes when compiling cpp files, but recompile is ok.

**Comment by GavinPayne** [comment]
It seems to Add include file search path by "-I /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/", maybe "-I /usr/include/" also need.

**Comment by SanDiegoXu** [comment]
I have tried your suggest, it seems partly valid.

But then I hava other problems， such as 
`…/XcodeDefault.xctoolchain/usr/include/c++/v1/iosfwd:90:10: fatal error: 
      'wchar.h' file not found`
and
`'string.h' file not found`
and so on .

I think when I add the path  "……/c++/v1", codes can find those .h files about C++, but can't find .h files about C. So, can you give me another suggest?
Thank you .

@GavinPayne

**Comment by GavinPayne** [comment]
Maybe you need install xcode command tools, open shell and run "xcode-select --install".  @SanDiegoXu 
I'm not sure this will work.

**Comment by SanDiegoXu** [comment]
Thank you very much! It's the key point.

I just run the commands to install toolchains in terminal. Then I solve the problem.

@GavinPayne

**Comment by SanDiegoXu** [comment]
Summary:
1. run "xcode-select --install" to install 'xcode-select' in command terminal
2.If it doesn't work, try to add a parameter     "-I /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/"

Thank you for @GavinPayne

**Comment by landrufang** [comment]
add the search path solve my problem . thanks

**Comment by 490694561** [comment]
> add the search path solve my problem . thanks

how to do it, it waste me too much time @landrufang

**Comment by code-football-dog** [comment]
on mac, i run "clang -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1/ -o a  demo.c",  result: "'stdio.h' file not found"
