### ISSUE TITLE
loaded libLTO doesn't support -bitcode_hide_symbols

### ISSUE THREAD

**Issue by ethanguan26** [obfuscator-llvm/obfuscator#83]
I followed the usage at wiki, and everything goes on well,I can run and debug my iOS project,but when I tried to archive, an error has occurred:
```
ld: loaded libLTO doesn't support -bitcode_hide_symbols: Obfuscator-LLVM version 4.0.1 for architecture armv7
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
```
What can I do to solve the problem?
Hope someone can help me, thanks.

**Comment by uraj** [comment]
-bitcode_hid_symbols is an Apple-only flag. You probably need to port the obfuscation part to the clang version customized by Apple, which is available at [here](https://opensource.apple.com/release/developer-tools-821.html).

**Comment by ethanguan26** [comment]
@uraj Thanks for your reply. I tried to disable the bitcode in my iOS project, then it count archive. 
But I don't know how to make the OLLVM to support the bitcode.

**Comment by uraj** [comment]
@GuanyiLL Like I said, that flag is only available in Apple's clang. Upstream clang or llvm simply does not support it. I would say the easiest work around to try is to add that flag in OLLVM without making that flag actually do anything. But I'm not sure if that will get you iOS code fitting all Apple's regulations.

**Comment by ethanguan26** [comment]
@uraj Ok,I know what you mean, thanks for your help.😊
