### ISSUE TITLE
cannot specify -o when generating multiple output files

### ISSUE THREAD

**Issue by x5forever** [obfuscator-llvm/obfuscator#84]
clang-4.0: error: cannot specify -o when generating multiple output files
Command /Users/x5/bin/obfuscator/build/bin/clang failed with exit code 1
In Xcode9.0

**Comment by 723937936** [comment]
how to solve this problem?

**Comment by x5forever** [comment]
@723937936 
You can remove it by disabling the build option Index-While-Building Functionality in Xcode.

**Comment by liyongjie1002** [comment]
how to do  it

**Comment by liyongjie1002** [comment]
how to do  it
