### ISSUE TITLE
compile error on xcode9 , can you fix the bug and update

### ISSUE THREAD

**Issue by x5forever** [obfuscator-llvm/obfuscator#86]
@obfuscator-llvm

**Comment by wonyee** [comment]
In XCode 9, set "Enable Index-While-Building Functionality" to No in Build Settings,  maybe it will solve the problem

**Comment by x5forever** [comment]
@wonyee 
Thank you for your comment.
I has set "Enable Index-While-Building Functionality" to No, but it still has other errors.
You can run normally in Xcode 9?

**Comment by wonyee** [comment]
@x5forever Yes I can run normally in Xcode 9.

**Comment by GJ641102478** [comment]
ollvm 使用的是llvm4.0,必须更新到5.0才可以

**Comment by x5forever** [comment]
非常感谢，我稍后试下，有问题，我再问你哈。。。多谢了


原始邮件
发件人:Guonotifications@github.com
收件人:obfuscator-llvm/obfuscatorobfuscator@noreply.github.com
抄送:x5foreverx5forever@163.com; Mentionmention@noreply.github.com
发送时间:2017年11月7日(周二) 16:53
主题:Re: [obfuscator-llvm/obfuscator] compile error on xcode9 , can youfix the bug and update (#86)


ollvm 使用的是llvm4.0,必须更新到5.0才可以

**Comment by x5forever** [comment]
@wonyee 
Which version of LLVM do you use? 4.0 or 5.0？

**Comment by csc-EricWu** [comment]
@DevGuoJ 大哥怎么更新到5.0  ？

**Comment by TheJoker-IOS** [comment]
I got error if I add -enable-strcry on flags c++
