### ISSUE TITLE
error: can't exec '/XXXX/build/bin' (Permission denied)

### ISSUE THREAD

**Issue by Bogon** [obfuscator-llvm/obfuscator#91]
Hello：
Can you help me with this problem?

error: can't exec '/Users/XXXX/Obfuscated_Tools/build/bin' (Permission denied)
Xcode 9.0.1

**Comment by cryptopathe** [comment]
Why would you execute a directory ? The compiler is `clang` and is contained in `/Users/XXXX/Obfuscated_Tools/build/bin/`.

**Comment by Bogon** [comment]
Thx!!  I solved it.   How do you run on xcode9.0.1?

**Comment by x5forever** [comment]
I have the same issue that can't run on xcode9, but it's ok on xcode8

**Comment by x5forever** [comment]
@cryptopathe
