### ISSUE TITLE
error: can't exec '/path/to/obfuscator_bin/clang' (No such file or directory) Command /path/to/obfuscator_bin/clang failed with exit code 71

### ISSUE THREAD

**Issue by liyongjie1002** [obfuscator-llvm/obfuscator#96]
error: can't exec '/path/to/obfuscator_bin/clang' (No such file or directory)
Command /path/to/obfuscator_bin/clang failed with exit code 71

how to resolve it?

**Comment by liyongjie1002** [comment]
I config it follow the document

**Comment by liyongjie1002** [comment]
I know ,the path /path/to/obfuscator_bin/clang is wrong ,use right clang path replace

**Comment by CrabMen** [comment]
@iyongjie ,hello，I have the same problem。But I didn‘t find the clang paht in xcode to change the clang path,clould you tell me where should I modify the clang path ，thx。
